## Name - Gaurang Vivek Sonkavde

## Class - M.Tech AI-ML

## PRN Number - 21070149023 

## Subject - Unsupervised Learning

# 2.2 ) Array Searching and Sorting

### Import Library

In [1]:
import numpy as np

### Sort along first and last Axis

In [3]:

# sort along the first axis
a = np.array([[15, 10], [14, 5]])
arr1 = np.sort(a, axis = 0)        
print ("Along first axis : \n", arr1)        
 
 
# sort along the last axis
a = np.array([[10, 15], [12, 5]])
arr2 = np.sort(a, axis = -1)        
print ("\nAlong first axis : \n", arr2)
 
#Sort along none Axis
a = np.array([[15, 10], [14, 5]])
arr1 = np.sort(a, axis = None)        
print ("\nAlong none axis : \n", arr1)

Along first axis : 
 [[14  5]
 [15 10]]

Along first axis : 
 [[10 15]
 [ 5 12]]

Along none axis : 
 [ 5 10 14 15]


In [5]:
# Counting a number of 
# non-zero values
a = np.count_nonzero([[0,8,0,4,0],[3,4,0,2,15]])
b = np.count_nonzero([[4,8,7,0,0],[3,4,0,0,45]], axis=0)

print("Number of nonzero values is :",a)
print("Number of nonzero values is :",b)

Number of nonzero values is : 6
Number of nonzero values is : [2 2 1 0 1]
