## Name - Gaurang Vivek Sonkavde

## Class - M.Tech AI-ML

## PRN Number - 21070149023 

## Subject - Unsupervised Learning

# 2) Apply the libraries of Pandas and numpy for Various Programs

# Matrix Programs

### Write a program for Matrix Addition

In [1]:
import numpy as np

In [6]:
a1 = np.array([[10,25,32], [26,15,11]])
a2 = np.array([[3,4,5], [16,12,22]])

print("a1: \n", a1, '\n')
print("a2: \n", a2, '\n')
      
b = np.add(a1,a2)
print("After Addition : \n", b)

a1: 
 [[10 25 32]
 [26 15 11]] 

a2: 
 [[ 3  4  5]
 [16 12 22]] 

After Addition : 
 [[13 29 37]
 [42 27 33]]


### Matrix Addition and Substraction Program

In [13]:
#Addition of Complex Number

c1 = complex(6, 4)
c2 = complex(7, 3)
print("Complex Number 1 : ",c1)
print("Complex Number 2 : ",c2)

c3 = np.add(c1,c2)
print("Addition of Complex Number :",c3)

Complex Number 1 :  (6+4j)
Complex Number 2 :  (7+3j)
Addition of Complex Number : (13+7j)


In [12]:
# Substarction of Complex Number

c1 = complex(7, 9)
c2 = complex(3, 5)
print("Complex Number 1 : ",c1)
print("Complex Number 2 : ",c2)

c3 = np.subtract(c1,c2)
print("Substraction of Complex Number : ",c3)


Complex Number 1 :  (7+9j)
Complex Number 2 :  (3+5j)
Substraction of Complex Number :  (4+4j)


### Matrix Multiplication Program

In [14]:
a1 = np.array([[5,4], [5,9]])
a2 = np.array([[6,2], [2,6]])

print("a1: \n", a1, '\n')
print("a2: \n", a2, '\n')
      
b = np.matmul(a1,a2)
print("After multiplication : \n", b)

a1: 
 [[5 4]
 [5 9]] 

a2: 
 [[6 2]
 [2 6]] 

After multiplication : 
 [[38 34]
 [48 64]]
